### ISSUE TITLE
how to build phoneset for a language using phonology.json

### ISSUE THREAD

**Issue by mirfan899** [google/language-resources#24]
I'm trying to build `phoneset` for chinese language, still stuck on how to use `apply_phonology.py`. I've tried to use it and getting issues with regex
https://github.com/google/language-resources/blob/9a7c2c685a16ff77ac7f28b3d0786204a1bd6db6/festival_utils/apply_phonology.py#L39

Here is what I'm getting when I try to build necessary files.
```shell
$ python apply_phonology.py cantonese_phonology.json cantonese/data/
Traceback (most recent call last):
  File "apply_phonology.py", line 774, in <module>
    main(sys.argv)
  File "apply_phonology.py", line 739, in main
    assert len(phoneset_paths) == 1
AssertionError
```

**Comment by mirfan899** [comment]
My mistake I've found the solution. Files should exist in a directory to build necessary files.
